package com.example.androidfinalproject.CarChargingStation;

public class CarChargingStation {
    /**
     * Initialization of variables that define a charging station object
     */
    private String title;
    private String latitude;
    private String longitude;
    private String telephone;
    private String streetAddress;
    private double distance;
    private boolean favourite;


    public CarChargingStation(){
        this.title = "";
        this.latitude = "";
        this.longitude = "";
        this.telephone = "";
        this.streetAddress = "";
        this.distance=0.0;
        this.favourite=false;
    }


    public CarChargingStation(String title, String latitude, String longitude, String telephone, String streetAddress, double distance){
        this.title = title;
        this.latitude = latitude;
        this.longitude = longitude;
        this.telephone = telephone;
        this.streetAddress = streetAddress;
        this.distance=distance;
        this.favourite=false;



    }

    /**
     * Alt-Insert/Autogenerated Getters and setters for all the variables.
     * I think some of these are unnecessary. I may delete them later.
     * @return
     */
    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getLatitude() {
        return latitude;
    }

    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    public String getLongitude() {
        return longitude;
    }

    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    public String getTelephone() {
        return telephone;
    }

    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    public String getStreetAddress() {
        return streetAddress;
    }

    public void setStreetAddress(String streetAddress) {
        this.streetAddress = streetAddress;
    }

    public double getDistance() {
        return distance;
    }

    public void setDistance(double distance) {
        this.distance = distance;
    }

    public boolean isFavourite() {
        return favourite;
    }

    public void setFavourite(boolean favourite) {
        this.favourite = favourite;
    }
}
